spring.application.name=careerprofile
spring.thymeleaf.cache=false
spring.datasource.url=jdbc:postgresql://localhost:5432/careerprofile
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

